### ISSUE TITLE
Un Protected

### ISSUE THREAD

**Issue by GWDdoS** [MathisLav/GeometryDashCE#6]
Can I have the unprotected files please?

**Comment by MathisLav** [comment]
What do you call "unprotected"? Is there any protected file in the repo?

**Comment by GWDdoS** [comment]
Well I cant change the program i cant add or remove or change anything

**Comment by GWDdoS** [comment]
the AGD
files

**Comment by MathisLav** [comment]
A little bit late but all assembly programs are protected because the code of the program can't be modified as is. You cannot modify an assembly program directly on your calc. Instead, you have to modify the code on your PC, then recompile the program and transfer it onto your calculator.

All the code is available in this repository. Feel free to modify it, information are available in the README.

**Comment by GWDdoS** [comment]
I cant compile it for some reason Thats why I ask

**Comment by MathisLav** [comment]
Well, what's the issue ? What's the error message etc... I cannot help you if you don't give me information about your problem.

**Comment by MathisLav** [comment]
Closing for now. If you give more information, please reopen and I'll try to help you.

**Comment by GWDdoS** [comment]
Sorry
i didnt see these
